version: '3.8'

services:
  dispatch:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: fwdslsh/dispatch:latest
    container_name: dispatch
    ports:
      - '3030:3030'
    environment:
      - TERMINAL_KEY=change-me-in-production
      - PTY_MODE=shell
      - ENABLE_TUNNEL=false
      # Directory management configuration
      - DISPATCH_CONFIG_DIR=/home/appuser/.config/dispatch
      - DISPATCH_PROJECTS_DIR=/var/lib/dispatch/projects
      - CONTAINER_ENV=true
      # Uncomment for public access:
      # - ENABLE_TUNNEL=true
      # - LT_SUBDOMAIN=my-dispatch
    volumes:
      # Mount for persistent project storage
      - dispatch_projects:/var/lib/dispatch/projects
      # Mount for persistent configuration
      - dispatch_config:/home/appuser/.config/dispatch
      # Optional: Mount host directories for persistence
      # - ./dispatch-projects:/var/lib/dispatch/projects
      # - ./dispatch-config:/home/appuser/.config/dispatch
    restart: unless-stopped

volumes:
  # Named volumes for project and configuration persistence
  dispatch_projects:
    driver: local
  dispatch_config:
    driver: local
