version: '3.8'

services:
  dispatch:
    # Use pre-built image from Docker Hub by default
    image: fwdslsh/dispatch:latest
    # Uncomment the build section below if you want to build locally instead:
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile
    container_name: dispatch
    ports:
      - '3030:3030'
    environment:
      - TERMINAL_KEY=change-me-in-production
      - PTY_MODE=shell
      - ENABLE_TUNNEL=false
      # Directory paths inside container
      - DISPATCH_CONFIG_DIR=/config
      - DISPATCH_PROJECTS_DIR=/projects
      - CONTAINER_ENV=true
      # Uncomment for public access:
      # - ENABLE_TUNNEL=true
      # - LT_SUBDOMAIN=my-dispatch
    volumes:
      # Mount two folders: config and projects
      # The container runs as root internally so it can write to these
      # without changing host permissions
      - ./dispatch-config:/config
      - ./dispatch-projects:/projects
      # Workspace for temporary files
      - ./dispatch-workspace:/workspace
    restart: unless-stopped
