version: '3.8'

services:
  # Nginx reverse proxy with Let's Encrypt SSL
  nginx:
    image: nginx:alpine
    container_name: dispatch-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    depends_on:
      - dispatch
    restart: unless-stopped
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  # Let's Encrypt certificate manager
  certbot:
    image: certbot/certbot
    container_name: dispatch-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  # Main Dispatch application
  dispatch:
    # Use pre-built image from Docker Hub by default
    image: fwdslsh/dispatch:latest
    # Uncomment the build section below if you want to build locally instead:
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile
    container_name: dispatch-app
    # Only expose port internally to nginx (not to host)
    expose:
      - '3030'
    environment:
      - TERMINAL_KEY=${TERMINAL_KEY:-change-me-in-production}
      - ENABLE_TUNNEL=false
      # SSL is handled by nginx reverse proxy
      - SSL_ENABLED=false
      # Directory paths inside container
      - DISPATCH_CONFIG_DIR=/config
      - DISPATCH_PROJECTS_DIR=/projects
      - DISPATCH_WORKSPACE_DIR=/workspace
      - CONTAINER_ENV=true
      # Trust proxy headers from nginx
      - TRUST_PROXY=true
      # Uncomment for public access via LocalTunnel (not recommended with SSL):
      # - ENABLE_TUNNEL=true
      # - LT_SUBDOMAIN=my-dispatch
    volumes:
      # Mount configuration and project directories
      - ./dispatch-config:/config
      - ./dispatch-projects:/projects
      # Workspace for temporary files
      - ./dispatch-workspace:/workspace
    restart: unless-stopped

# Create named volumes for SSL certificates (optional but recommended for persistence)
volumes:
  letsencrypt_conf:
  letsencrypt_www:
