name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:

  # Then create the release
  release:
    name: Create Release
    uses: fwdslsh/toolkit/.github/workflows/create-gh-release.yml@main
    with:
      tag: ${{ github.event.inputs.tag || github.ref_name }}
    secrets: inherit

  # Call Docker publishing workflow
  docker:
    name: Publish Docker Image
    needs: [release]
    if: ${{ !cancelled() && needs.release.result == 'success' }}
    uses: fwdslsh/toolkit/.github/workflows/publish-docker.yml@main
    with:
      tag:  ${{ github.event.inputs.tag || github.ref_name }}
      description: Accessible web-based terminal sessions with AI assistance.
      image_name: fwdslsh/dispatch      
    secrets: inherit

