name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:

  # Then create the release
  release:
    name: Create GitHub Release
    uses: softprops/action-gh-release@v2
    with:
      tag_name: ${{ github.event.inputs.tag || github.ref_name }}
      name: ${{ github.event.inputs.tag || github.ref_name }}
      body_path: .github/workflows/release_notes.md
      generate_release_notes: true
      append_body: true
  # Call Docker publishing workflow
  docker:
    name: Publish Docker Image
    needs: [release]
    if: ${{ !cancelled() && needs.release.result == 'success' }}
    uses: fwdslsh/toolkit/.github/workflows/publish-docker.yml@main
    with:
      tag:  ${{ github.event.inputs.tag || github.ref_name }}
      description: Accessible web-based terminal sessions with AI assistance.
    secrets: inherit

